name: Build EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu118
          pip install pyinstaller

      # 执行 build_single.bat
      - name: Build single exe
        run: .\release\build_single.bat
        shell: cmd

      # 执行 build_multi.bat
      - name: Build multi exe
        run: .\release\build_multi.bat
        shell: cmd

      # 上传产物 (dist_single + dist_multi 文件夹)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: exe-builds
          path: |
            release/dist_single/**
            release/dist_multi/**
